import type {
  Comment,
  Post,
  Topic,
  User,
  Friendship,
  Follow,
  ChatThread,
  ChatMessage,
  NotificationItem,
} from "./types";
import { clusterIdFor } from "./similarity";

const now = Date.now();
const hoursAgo = (h: number) => new Date(now - h * 3600_000).toISOString();
const daysAgo = (d: number) => new Date(now - d * 86400_000).toISOString();

export const SERVICE_USER_ID = "u_service";
export const ADMIN_USER_ID = "u5";

export const seedUsers: User[] = [
  {
    id: SERVICE_USER_ID,
    username: "connecthub_curator",
    displayName: "ConnectHub Curator",
    bio: "Public service account that publishes daily curated shorts, music, and news for everyone.",
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Curator",
    profilePublic: true,
    joinedAt: daysAgo(500),
    location: "Everywhere",
    interests: ["curation", "tech", "music", "shorts"],
    followersCount: 50000,
    followingCount: 0,
    friendsCount: 0,
    postsCount: 0,
    rating: 5,
    isService: true,
    isAdmin: true,
  },
  {
    id: "u1",
    username: "maya_waves",
    displayName: "Maya Waves",
    bio: "Short-form storyteller · music nights · community host",
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Maya",
    profilePublic: true,
    joinedAt: daysAgo(420),
    location: "Lisbon",
    interests: ["music", "shorts", "travel"],
    followersCount: 12840,
    followingCount: 312,
    friendsCount: 86,
    postsCount: 214,
    rating: 4.9,
  },
  {
    id: "u2",
    username: "jordan_ink",
    displayName: "Jordan Ink",
    bio: "Illustrator sharing process clips and warm community tips",
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Jordan",
    profilePublic: true,
    joinedAt: daysAgo(210),
    location: "Toronto",
    interests: ["art", "design", "community"],
    followersCount: 6420,
    followingCount: 188,
    friendsCount: 54,
    postsCount: 97,
    rating: 4.7,
  },
  {
    id: "u3",
    username: "nova_beats",
    displayName: "Nova Beats",
    bio: "Curating feel-good tracks from artists you already love",
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Nova",
    profilePublic: true,
    joinedAt: daysAgo(90),
    location: "Seoul",
    interests: ["music", "producers", "live"],
    followersCount: 22100,
    followingCount: 401,
    friendsCount: 120,
    postsCount: 310,
    rating: 4.95,
  },
  {
    id: "u4",
    username: "sam_quiet",
    displayName: "Sam Quiet",
    bio: "Private by default — friends only for deep dives",
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=Sam",
    profilePublic: false,
    joinedAt: daysAgo(60),
    location: "Austin",
    interests: ["books", "film"],
    followersCount: 890,
    followingCount: 120,
    friendsCount: 18,
    postsCount: 22,
    rating: 4.2,
  },
  {
    id: "u5",
    username: "you",
    displayName: "You",
    bio: "Welcome to ConnectHub — update your bio anytime",
    avatarUrl: "https://api.dicebear.com/9.x/avataaars/svg?seed=You",
    profilePublic: true,
    joinedAt: daysAgo(2),
    location: "Anywhere",
    interests: ["community", "music", "shorts", "tech"],
    followersCount: 12,
    followingCount: 8,
    friendsCount: 3,
    postsCount: 2,
    rating: 4.0,
    isAdmin: true,
  },
];

export const seedTopics: Topic[] = [
  {
    id: "t1",
    slug: "music",
    name: "Music",
    description: "Artist drops, playlists, and listening rooms kept on-platform.",
    postCount: 48,
    color: "#5B8DEF",
  },
  {
    id: "t2",
    slug: "shorts",
    name: "Shorts",
    description: "Vertical clips ingested for in-app viewing — no outbound hops.",
    postCount: 62,
    color: "#3D9B8F",
  },
  {
    id: "t3",
    slug: "community",
    name: "Community",
    description: "Warm board chats, introductions, and local meetups.",
    postCount: 35,
    color: "#E8A87C",
  },
  {
    id: "t4",
    slug: "creators",
    name: "Creators",
    description: "Behind-the-scenes from popular ConnectHub voices.",
    postCount: 28,
    color: "#7B6CF6",
  },
  {
    id: "t5",
    slug: "wellness",
    name: "Wellness",
    description: "Gentle check-ins, walks, and feel-good habits.",
    postCount: 19,
    color: "#6BBF8A",
  },
  {
    id: "t6",
    slug: "tech",
    name: "Tech",
    description: "Daily curated tech from HN, TechCrunch, Verge, GitHub, and more.",
    postCount: 24,
    color: "#4A90A4",
  },
];

export const curatedShortIds = [
  {
    id: "aqz-KE-bpKQ",
    title: "Big Buck Bunny moments",
    channel: "Blender Foundation",
    tags: ["shorts", "animation"],
  },
  {
    id: "LXb3EKWsInQ",
    title: "Coastal calm reel",
    channel: "Nature Desk",
    tags: ["shorts", "travel"],
  },
  {
    id: "ScMzIvxBSi4",
    title: "Studio session snippet",
    channel: "Studio Loop",
    tags: ["shorts", "music"],
  },
  {
    id: "jNQXAC9IVRw",
    title: "First camera laughs",
    channel: "Museum Clips",
    tags: ["shorts", "community"],
  },
];

export const curatedArtists = [
  {
    artist: "Billie Eilish",
    track: "Birds of a Feather",
    album: "Hit Me Hard and Soft",
    genre: "Pop",
    youtubeVideoId: "V9PVRfjEBTI",
    description:
      "Soft-edged pop with intimate vocal layering — streamed in-app so the conversation stays on ConnectHub.",
  },
  {
    artist: "Taylor Swift",
    track: "Cruel Summer",
    album: "Lover",
    genre: "Pop",
    youtubeVideoId: "ic8j13piAhQ",
    description:
      "Summer-bright hooks and crowd energy. Details enriched from artist catalog metadata.",
  },
  {
    artist: "The Weeknd",
    track: "Blinding Lights",
    album: "After Hours",
    genre: "Synth-pop",
    youtubeVideoId: "4NRXx6U8ABQ",
    description:
      "Neon synth pulse and 80s nostalgia — playable inside the card, no external redirect.",
  },
  {
    artist: "Bad Bunny",
    track: "DtMF",
    album: "Nadie Sabe Lo Que Va a Pasar Mañana",
    genre: "Reggaeton",
    youtubeVideoId: "saGYMhApaP8",
    description:
      "Island rhythm and bilingual wordplay. Music feed curated for community listening.",
  },
  {
    artist: "SZA",
    track: "Snooze",
    album: "SOS",
    genre: "R&B",
    youtubeVideoId: "UowPNx9bOGI",
    description:
      "Velvet R&B ballad energy — comments and reactions stay nested under the post.",
  },
];

export function buildSeedPosts(): Post[] {
  const shorts = curatedShortIds.map((s, i) => {
    const tags = s.tags;
    return {
      id: `ps${i + 1}`,
      authorId: SERVICE_USER_ID,
      kind: "short" as const,
      title: s.title,
      body: `${s.title} — full description for in-app viewing. Channel: ${s.channel}. Tags: ${tags.join(", ")}. What moment should we talk about in comments?`,
      topicIds: ["t2", tags.includes("music") ? "t1" : "t3"],
      createdAt: hoursAgo(2 + i * 5),
      updatedAt: hoursAgo(2 + i * 5),
      upvotes: 120 + i * 37,
      downvotes: 2 + (i % 3),
      likes: 80 + i * 21,
      commentCount: 4 + i,
      media: {
        title: s.title,
        description: `Auto-ingested short with enriched metadata: channel “${s.channel}”, tags [${tags.join(", ")}], portrait framing for full-bleed mobile width.`,
        channelTitle: s.channel,
        youtubeVideoId: s.id,
        durationSec: 45 + i * 8,
        publishedAt: daysAgo(1 + i),
        viewCount: 50000 + i * 12000,
        likeCount: 3200 + i * 400,
        tags,
        thumbnailUrl: `https://i.ytimg.com/vi/${s.id}/hqdefault.jpg`,
        width: 1080,
        height: 1920,
        orientation: "portrait" as const,
      },
      sourceHidden: true,
      bookmarkedBy: i === 0 ? ["u5"] : [],
      likedBy: ["u5"],
      voters: { u5: 1 as const },
      fingerprint: `yt:${s.id}`,
      sourcePlatform: "youtube" as const,
      sourceGroup: "YouTube Channels",
      clusterId: clusterIdFor("youtube", tags, ["t2"]),
    };
  });

  const music = curatedArtists.map((a, i) => {
    const tags = ["music", a.genre.toLowerCase(), a.artist.toLowerCase().replace(/\s+/g, "-")];
    return {
      id: `pm${i + 1}`,
      authorId: "u3",
      kind: "music" as const,
      title: `${a.artist} — ${a.track}`,
      body: a.description,
      topicIds: ["t1"],
      createdAt: hoursAgo(1 + i * 3),
      updatedAt: hoursAgo(1 + i * 3),
      upvotes: 200 + i * 55,
      downvotes: 1,
      likes: 150 + i * 40,
      commentCount: 6 + i,
      media: {
        title: a.track,
        artist: a.artist,
        album: a.album,
        genre: a.genre,
        description: a.description,
        youtubeVideoId: a.youtubeVideoId,
        durationSec: 180 + i * 12,
        tags,
        thumbnailUrl: `https://i.ytimg.com/vi/${a.youtubeVideoId}/hqdefault.jpg`,
        channelTitle: a.artist,
        publishedAt: daysAgo(30 + i * 10),
        viewCount: 1_000_000 + i * 250_000,
        likeCount: 40_000 + i * 5_000,
        width: 1920,
        height: 1080,
        orientation: "landscape" as const,
      },
      sourceHidden: true,
      bookmarkedBy: i < 2 ? ["u5"] : [],
      likedBy: i % 2 === 0 ? ["u5"] : [],
      voters: {},
      fingerprint: `yt:${a.youtubeVideoId}`,
      sourcePlatform: "music" as const,
      sourceGroup: "Music Artists",
      clusterId: clusterIdFor("music", tags, ["t1"]),
    };
  });

  const curatedNews: Post[] = [
    {
      id: "pn_tc1",
      authorId: SERVICE_USER_ID,
      kind: "article",
      title: "AI startup raises Series B to automate research desks",
      body: "TechCrunch-style digest: funding, product angle, and what it means for builders. Discussion: which workflow would you automate first? External links removed.",
      topicIds: ["t6"],
      createdAt: hoursAgo(3),
      updatedAt: hoursAgo(3),
      upvotes: 142,
      downvotes: 4,
      likes: 88,
      commentCount: 11,
      imageUrls: [
        "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1600&q=80",
      ],
      media: {
        title: "Series B research automation",
        description:
          "Seeded TechCrunch-group article with funding details, target buyers, and comment hooks for founders.",
        channelTitle: "techcrunch",
        tags: ["tech", "startups", "funding", "ai"],
        orientation: "landscape",
        width: 1600,
        height: 900,
        publishedAt: hoursAgo(4),
      },
      sourceHidden: true,
      bookmarkedBy: [],
      likedBy: [],
      voters: {},
      fingerprint: "seed:techcrunch:series-b",
      sourcePlatform: "techcrunch",
      sourceGroup: "Tech & Business Media",
      clusterId: clusterIdFor("techcrunch", ["startups", "ai"], ["t6"]),
    },
    {
      id: "pn_verge1",
      authorId: SERVICE_USER_ID,
      kind: "news",
      title: "The Verge: Foldables get a practical software rethink",
      body: "Consumer electronics roundup with UX notes for dual screens. Prompt: would you daily-drive a foldable for ConnectHub short creation?",
      topicIds: ["t6"],
      createdAt: hoursAgo(5),
      updatedAt: hoursAgo(5),
      upvotes: 97,
      downvotes: 2,
      likes: 61,
      commentCount: 7,
      imageUrls: [
        "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1600&q=80",
      ],
      media: {
        title: "Foldables software rethink",
        description: "Product launch coverage clustered under Tech & Business Media.",
        channelTitle: "theverge",
        tags: ["tech", "gadgets", "mobile"],
        orientation: "landscape",
        width: 1600,
        height: 1000,
      },
      sourceHidden: true,
      bookmarkedBy: ["u5"],
      likedBy: [],
      voters: {},
      fingerprint: "seed:verge:foldables",
      sourcePlatform: "theverge",
      sourceGroup: "Tech & Business Media",
      clusterId: clusterIdFor("theverge", ["gadgets"], ["t6"]),
    },
    {
      id: "pn_hn1",
      authorId: SERVICE_USER_ID,
      kind: "news",
      title: "Show HN: Local-first sync engine for community apps",
      body: "Hacker News digest: offline-first CRDTs for feeds and comments. Prompt: would ConnectHub benefit from local-first drafts?",
      topicIds: ["t6"],
      createdAt: hoursAgo(7),
      updatedAt: hoursAgo(7),
      upvotes: 310,
      downvotes: 6,
      likes: 120,
      commentCount: 44,
      media: {
        title: "Local-first sync",
        description: "Developer-heavy HN thread summary — Social News Aggregators group.",
        channelTitle: "HN",
        tags: ["hackernews", "startups", "developers"],
        viewCount: 310,
        likeCount: 44,
        orientation: "landscape",
      },
      sourceHidden: true,
      bookmarkedBy: [],
      likedBy: ["u5"],
      voters: { u5: 1 },
      fingerprint: "seed:hn:local-first",
      sourcePlatform: "hackernews",
      sourceGroup: "Social News Aggregators",
      clusterId: clusterIdFor("hackernews", ["developers"], ["t6"]),
    },
    {
      id: "pn_reddit1",
      authorId: SERVICE_USER_ID,
      kind: "news",
      title: "r/technology: Chip shortage ripple into indie hardware",
      body: "Hot Reddit thread summary (score threshold met). Prompt: how should community makers plan inventory this quarter?",
      topicIds: ["t6"],
      createdAt: hoursAgo(9),
      updatedAt: hoursAgo(9),
      upvotes: 420,
      downvotes: 18,
      likes: 95,
      commentCount: 130,
      media: {
        title: "Chip shortage ripple",
        description: "Reddit aggregator group — high-engagement discussion bait.",
        channelTitle: "r/technology",
        tags: ["reddit", "technology", "hardware"],
        viewCount: 420,
        likeCount: 130,
        orientation: "landscape",
      },
      sourceHidden: true,
      bookmarkedBy: [],
      likedBy: [],
      voters: {},
      fingerprint: "seed:reddit:chips",
      sourcePlatform: "reddit",
      sourceGroup: "Social News Aggregators",
      clusterId: clusterIdFor("reddit", ["hardware"], ["t6"]),
    },
    {
      id: "pn_gh1",
      authorId: SERVICE_USER_ID,
      kind: "article",
      title: "Trending: openai/whisper",
      body: "GitHub Trending digest — speech recognition framework exploding in stars. Prompt: where would you embed Whisper inside ConnectHub?",
      topicIds: ["t6"],
      createdAt: hoursAgo(11),
      updatedAt: hoursAgo(11),
      upvotes: 188,
      downvotes: 1,
      likes: 76,
      commentCount: 19,
      media: {
        title: "openai/whisper",
        description: "Developer Hubs group — OSS momentum for AI audio.",
        channelTitle: "GitHub Trending",
        tags: ["github", "opensource", "python", "ai"],
        likeCount: 78000,
        orientation: "landscape",
      },
      sourceHidden: true,
      bookmarkedBy: [],
      likedBy: [],
      voters: {},
      fingerprint: "github:openai/whisper",
      sourcePlatform: "github",
      sourceGroup: "Developer Hubs",
      clusterId: clusterIdFor("github", ["ai", "python"], ["t6"]),
    },
    {
      id: "pn_wired1",
      authorId: SERVICE_USER_ID,
      kind: "article",
      title: "Wired: The quiet ethics of recommendation loops",
      body: "Long-form feature digest on engagement systems. Prompt: how should ConnectHub’s similar-post suggestions stay healthy?",
      topicIds: ["t6", "t3"],
      createdAt: hoursAgo(14),
      updatedAt: hoursAgo(14),
      upvotes: 76,
      downvotes: 3,
      likes: 54,
      commentCount: 9,
      imageUrls: [
        "https://images.unsplash.com/photo-1555949963-aa79dcee981c?auto=format&fit=crop&w=1600&q=80",
      ],
      media: {
        title: "Recommendation ethics",
        description: "Wired cluster under Tech & Business Media.",
        channelTitle: "wired",
        tags: ["tech", "features", "ethics"],
        orientation: "landscape",
        width: 1600,
        height: 1000,
      },
      sourceHidden: true,
      bookmarkedBy: [],
      likedBy: [],
      voters: {},
      fingerprint: "seed:wired:recs",
      sourcePlatform: "wired",
      sourceGroup: "Tech & Business Media",
      clusterId: clusterIdFor("wired", ["ethics"], ["t6"]),
    },
    {
      id: "pn_devto1",
      authorId: SERVICE_USER_ID,
      kind: "article",
      title: "Dev.to: Building nested comments that feel human",
      body: "Engineering tutorial digest on threaded UX. Prompt: what nesting depth feels right on mobile?",
      topicIds: ["t6", "t3"],
      createdAt: hoursAgo(16),
      updatedAt: hoursAgo(16),
      upvotes: 64,
      downvotes: 0,
      likes: 41,
      commentCount: 12,
      media: {
        title: "Nested comments UX",
        description: "Developer Hubs — practical webdev write-up.",
        channelTitle: "devto",
        tags: ["webdev", "tutorials", "engineering"],
        orientation: "landscape",
      },
      sourceHidden: true,
      bookmarkedBy: [],
      likedBy: [],
      voters: {},
      fingerprint: "seed:devto:comments",
      sourcePlatform: "devto",
      sourceGroup: "Developer Hubs",
      clusterId: clusterIdFor("devto", ["webdev"], ["t6"]),
    },
  ];

  const community: Post[] = [
    {
      id: "pc1",
      authorId: "u2",
      kind: "image",
      title: "Warm board sketch of the week",
      body: "Soft pencil pass of our Friendly Cards layout moodboard. Drop nested feedback below.",
      topicIds: ["t3", "t4"],
      createdAt: hoursAgo(6),
      updatedAt: hoursAgo(6),
      upvotes: 89,
      downvotes: 0,
      likes: 64,
      commentCount: 3,
      imageUrls: [
        "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1600&q=80",
      ],
      media: {
        title: "Moodboard sketch",
        description: "Wide hero image for full-bleed phone layouts",
        width: 1600,
        height: 1000,
        tags: ["community", "design"],
        orientation: "landscape",
      },
      sourceHidden: true,
      bookmarkedBy: [],
      likedBy: [],
      voters: {},
      sourcePlatform: "community",
      sourceGroup: "Community",
      clusterId: clusterIdFor("community", ["design"], ["t3"]),
    },
    {
      id: "pc2",
      authorId: "u5",
      kind: "text",
      title: "Hello ConnectHub",
      body: "First post from my profile — looking for music friends and short-form collaborators. Say hi in the thread!",
      topicIds: ["t3"],
      createdAt: hoursAgo(10),
      updatedAt: hoursAgo(10),
      upvotes: 24,
      downvotes: 0,
      likes: 18,
      commentCount: 2,
      sourceHidden: true,
      bookmarkedBy: [],
      likedBy: [],
      voters: {},
      sourcePlatform: "community",
      sourceGroup: "Community",
      clusterId: clusterIdFor("community", ["intro"], ["t3"]),
    },
    {
      id: "pc3",
      authorId: "u1",
      kind: "image",
      title: "Portrait story frame",
      body: "Testing portrait media detection — tall image should fill phone width end-to-end.",
      topicIds: ["t2", "t4"],
      createdAt: hoursAgo(4),
      updatedAt: hoursAgo(4),
      upvotes: 55,
      downvotes: 1,
      likes: 33,
      commentCount: 1,
      imageUrls: [
        "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=900&q=80",
      ],
      media: {
        title: "Portrait frame",
        description: "Portrait orientation sample",
        width: 900,
        height: 1400,
        orientation: "portrait",
        tags: ["creators", "portrait"],
      },
      sourceHidden: true,
      bookmarkedBy: [],
      likedBy: [],
      voters: {},
      sourcePlatform: "community",
      sourceGroup: "Community",
      clusterId: clusterIdFor("community", ["portrait"], ["t2"]),
    },
  ];

  return [...music, ...shorts, ...curatedNews, ...community];
}

export function buildSeedComments(): Comment[] {
  return [
    {
      id: "c1",
      postId: "pm1",
      authorId: "u1",
      parentId: null,
      body: "This track hits differently in the evening feed.",
      createdAt: hoursAgo(0.5),
      upvotes: 12,
      downvotes: 0,
    },
    {
      id: "c2",
      postId: "pm1",
      authorId: "u5",
      parentId: "c1",
      body: "Agreed — love that we can discuss without leaving the page.",
      createdAt: hoursAgo(0.3),
      upvotes: 5,
      downvotes: 0,
    },
    {
      id: "c3",
      postId: "ps1",
      authorId: "u2",
      parentId: null,
      body: "Full-bleed short looks great on phone width.",
      createdAt: hoursAgo(1),
      upvotes: 8,
      downvotes: 0,
    },
    {
      id: "c4",
      postId: "pc2",
      authorId: "u3",
      parentId: null,
      body: "Welcome! Check Topics → Music for today’s artist feed.",
      createdAt: hoursAgo(8),
      upvotes: 3,
      downvotes: 0,
    },
    {
      id: "c5",
      postId: "pn_hn1",
      authorId: "u5",
      parentId: null,
      body: "Local-first drafts would help me write offline on the train.",
      createdAt: hoursAgo(2),
      upvotes: 9,
      downvotes: 0,
    },
    {
      id: "c6",
      postId: "pn_tc1",
      authorId: "u1",
      parentId: null,
      body: "Curious how they handle citation quality in research automation.",
      createdAt: hoursAgo(1.5),
      upvotes: 4,
      downvotes: 0,
    },
  ];
}

export function buildSeedSocial() {
  const friendships: Friendship[] = [
    {
      id: "f1",
      userId: "u5",
      friendId: "u1",
      status: "accepted",
      createdAt: daysAgo(1),
    },
    {
      id: "f2",
      userId: "u5",
      friendId: "u3",
      status: "accepted",
      createdAt: daysAgo(1),
    },
    {
      id: "f3",
      userId: "u2",
      friendId: "u5",
      status: "pending",
      createdAt: hoursAgo(4),
    },
  ];
  const follows: Follow[] = [
    { followerId: "u5", followingId: "u1", createdAt: daysAgo(1) },
    { followerId: "u5", followingId: "u3", createdAt: daysAgo(1) },
    { followerId: "u5", followingId: SERVICE_USER_ID, createdAt: daysAgo(1) },
    { followerId: "u1", followingId: "u5", createdAt: hoursAgo(20) },
    { followerId: "u2", followingId: "u3", createdAt: daysAgo(3) },
  ];
  const chats: ChatThread[] = [
    {
      id: "ch1",
      type: "peer",
      title: "Maya Waves",
      memberIds: ["u5", "u1"],
      lastMessageAt: hoursAgo(1),
      lastPreview: "Want to co-host a listening room?",
      status: "open",
    },
    {
      id: "ch2",
      type: "group",
      title: "Friday Music Circle",
      memberIds: ["u5", "u1", "u3", "u2"],
      lastMessageAt: hoursAgo(3),
      lastPreview: "Nova dropped three new artist cards",
      status: "open",
    },
    {
      id: "ch3",
      type: "peer",
      title: "Message request · Jordan Ink",
      memberIds: ["u5", "u2"],
      lastMessageAt: hoursAgo(2),
      lastPreview: "Hey — loved your sketch post",
      status: "request",
      requestedBy: "u2",
    },
  ];
  const messages: ChatMessage[] = [
    {
      id: "m1",
      threadId: "ch1",
      senderId: "u1",
      body: "Want to co-host a listening room?",
      createdAt: hoursAgo(1),
    },
    {
      id: "m2",
      threadId: "ch1",
      senderId: "u5",
      body: "Yes — keep it on ConnectHub so folks stay in chat.",
      createdAt: hoursAgo(0.8),
    },
    {
      id: "m3",
      threadId: "ch2",
      senderId: "u3",
      body: "Nova dropped three new artist cards",
      createdAt: hoursAgo(3),
    },
    {
      id: "m4",
      threadId: "ch3",
      senderId: "u2",
      body: "Hey — loved your sketch post",
      createdAt: hoursAgo(2),
    },
  ];
  const notifications: NotificationItem[] = [
    {
      id: "n1",
      userId: "u5",
      type: "friend_request",
      title: "Friend request",
      body: "Jordan Ink wants to connect — approve to become friends",
      href: "/friends",
      read: false,
      createdAt: hoursAgo(4),
    },
    {
      id: "n2",
      userId: "u5",
      type: "comment",
      title: "New comment",
      body: "Maya replied in Birds of a Feather",
      href: "/?focus=pm1",
      read: false,
      createdAt: hoursAgo(0.4),
    },
    {
      id: "n3",
      userId: "u5",
      type: "follow",
      title: "New follower",
      body: "Maya Waves started following you",
      href: "/users/u1",
      read: true,
      createdAt: hoursAgo(20),
    },
    {
      id: "n4",
      userId: "u5",
      type: "message_request",
      title: "Message request",
      body: "Jordan Ink sent a message request",
      href: "/chat?thread=ch3",
      read: false,
      createdAt: hoursAgo(2),
    },
    {
      id: "n5",
      userId: "u5",
      type: "incoming_message",
      title: "Incoming message",
      body: "Maya: Want to co-host a listening room?",
      href: "/chat?thread=ch1",
      read: false,
      createdAt: hoursAgo(1),
    },
  ];
  return { friendships, follows, chats, messages, notifications };
}
